#!/bin/bash

if ! command -v docker &> /dev/null
then
    echo "Please install Docker."
    echo "More info can be found here https://docs.docker.com/get-docker/."
    exit
fi


docker run -it --rm --name my-running-script -v "$PWD":/usr/src/myapp -w /usr/src/myapp php:8.0 php $1
